services:
  - type: web
    plan: free
    name: userbot
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & python3 -m userbot
    repo: https://github.com/rick1128/rickuserbot      
    branch: master
    envVars:
      - key: ALIVE_NAME 
        sync: false
      - key: TG_BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: APP_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_URL
        sync: false    
    autoDeploy: false
